- name: Add Helm repository
  command: helm repo add {{ helm_repo_name }} {{ helm_repo_url }}
  register: helm_repo_add

- name: Update Helm repositories
  command: helm repo update
  when: helm_repo_add is succeeded

- name: Deploy Helm release
  command: >
    helm upgrade --install {{ helm_release_name }} {{ helm_chart_name }}
    --namespace {{ helm_namespace }}
    --values {{ helm_values_file }}
  register: helm_deploy

- name: Verify Helm deployment status
  shell: kubectl rollout status deployment/{{ helm_release_name }} -n {{ helm_namespace }}
  when: helm_deploy is succeeded
